import type { TradeConfig } from '../types'

export const roofer: TradeConfig = {
  id: 'roofer',
  name: 'Roofer',
  emoji: '🏠',
  tagline: 'Trusted roofing — local, licensed, and guaranteed.',
  colorScheme: {
    navy: '#0D2113',
    navyHover: '#163320',
    accent: '#16A34A',
    accentInk: '#15803D',
    accentTint: '#F0FDF4',
  },
  sections: [
    {
      // Generated by src/gen, not picked from templates.
      type: 'hero',
      recommended: 'generated',
      variants: [],
    },
    {
      type: 'trust_bar',
      recommended: 'trust-bar-scroll',
      variants: [
        { id: 'trust-bar-scroll', label: 'Scroll strip', component: 'TrustBarScroll' },
        { id: 'trust-grid', label: 'Trust grid', component: 'TrustGrid' },
      ],
    },
    {
      type: 'services',
      recommended: 'services-grid',
      variants: [
        { id: 'services-grid', label: 'Cards + urgent', component: 'ServicesGrid' },
        { id: 'services-list', label: 'List rows', component: 'ServicesList' },
      ],
    },
    {
      type: 'why_us',
      recommended: 'why-features',
      variants: [
        { id: 'why-features', label: 'Feature rows', component: 'WhyUsFeatures' },
      ],
    },
    {
      type: 'testimonials',
      recommended: 'reviews-carousel',
      variants: [
        { id: 'reviews-carousel', label: 'Review carousel', component: 'ReviewsCarousel' },
      ],
    },
    {
      type: 'contact',
      recommended: 'contact-full',
      variants: [
        { id: 'contact-full', label: 'Full (hours + form)', component: 'ContactFull' },
        { id: 'contact-simple', label: 'Simple CTA', component: 'ContactSimple' },
      ],
    },
  ],
  ctaText: 'Get a Free Roof Inspection',
  ctaSubtext: 'No obligation — we come to you',
  trustSignals: ['30+ Years Experience', 'Fully Licensed & Insured', 'Manufacturer Warranty', 'Emergency Service Available', 'Free Estimates', 'Storm Damage Specialists'],
  services: ['Roof Replacement', 'Roof Repair', 'Gutters & Fascia', 'Storm Damage', 'Flat Roofing', 'Inspections'],
  stickyCallBar: false,
}
