// Copies the self-hosted fonts (latin subset, woff2) from @fontsource into public/fonts
// and writes public/fonts/fonts.css for the builder. Run with `npm run fonts` after
// changing the list. Generated sites use src/gen/fonts.ts, which must match FONTS here
// (a test checks this).
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'public', 'fonts')

/** family -> faces ("400", "400-italic"). Builder chrome first, then everything a site theme can use. */
const FONTS = {
  'Inter': ['400', '500', '600', '700'],
  'JetBrains Mono': ['400', '500'],
  'Anton': ['400'],
  'Barlow': ['400', '500', '600', '700'],
  'Barlow Condensed': ['600', '700'],
  'Schibsted Grotesk': ['700', '800'],
  'Instrument Sans': ['400', '500', '600', '700'],
  'Fraunces': ['400', '400-italic', '600'],
  'Libre Franklin': ['400', '500', '600', '700'],
  'Bricolage Grotesque': ['700', '800'],
  'Nunito Sans': ['400', '600', '700', '800'],
}

const slug = family => family.toLowerCase().replace(/ /g, '-')

mkdirSync(out, { recursive: true })
// Start clean so fonts dropped from the list don't linger.
for (const f of readdirSync(out)) if (f.endsWith('.woff2')) rmSync(join(out, f))
const faces = []
const licences = new Set()
for (const [family, list] of Object.entries(FONTS)) {
  const pkg = join(root, 'node_modules', '@fontsource', slug(family))
  licences.add(`${family}: ${JSON.parse(readFileSync(join(pkg, 'package.json'), 'utf8')).license}`)
  for (const face of list) {
    const [weight, style = 'normal'] = face.split('-')
    const file = `${slug(family)}-${face}.woff2`
    copyFileSync(join(pkg, 'files', `${slug(family)}-latin-${weight}-${style}.woff2`), join(out, file))
    faces.push(`@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;src:url('./${file}') format('woff2')}`)
  }
}
writeFileSync(join(out, 'fonts.css'), `/* Generated by scripts/copy-fonts.mjs. Self-hosted: no third-party font requests. */\n${faces.join('\n')}\n`)
writeFileSync(join(out, 'LICENSES.txt'), `Fonts from Fontsource (https://fontsource.org), latin subset.\n${[...licences].join('\n')}\nSIL Open Font License 1.1: https://openfontlicense.org\n`)
console.log(`Copied ${faces.length} font files to public/fonts`)
